"""The v2 core tables and columns from spec §7.2."""

import sqlite3

from .sql import execute_script

SCHEMA = """
-- Threads are v1 "chats"; table not renamed to keep v1 code/tests.
ALTER TABLE chats ADD COLUMN archived INTEGER NOT NULL DEFAULT 0;

ALTER TABLE messages ADD COLUMN kind TEXT NOT NULL DEFAULT 'text';
  -- 'text' (user/assistant conversation), 'tool', 'approval', 'signin', 'file', 'error', 'note'
ALTER TABLE messages ADD COLUMN meta TEXT;          -- JSON, <= 16 KB
ALTER TABLE messages ADD COLUMN run_id TEXT;
CREATE INDEX IF NOT EXISTS messages_chat_kind ON messages(chat_id, kind, id);

ALTER TABLE facts ADD COLUMN origin TEXT NOT NULL DEFAULT 'unknown';  -- 'agent' | 'panel' | 'unknown'
ALTER TABLE facts ADD COLUMN chat_id INTEGER;
ALTER TABLE facts ADD COLUMN tainted INTEGER NOT NULL DEFAULT 0;     -- saved during a tainted run

CREATE TABLE runs (
  id TEXT PRIMARY KEY,                 -- uuid4 hex
  origin TEXT NOT NULL CHECK (origin IN ('chat','job')),
  chat_id INTEGER REFERENCES chats(id) ON DELETE SET NULL,
  job_id INTEGER,
  job_run_id INTEGER,
  started REAL NOT NULL,
  finished REAL,
  status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running','done','error','stopped')),
  tainted INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE approvals (
  id TEXT PRIMARY KEY,                 -- secrets.token_urlsafe(16)
  run_id TEXT NOT NULL REFERENCES runs(id),
  chat_id INTEGER,
  job_id INTEGER,
  tool TEXT NOT NULL,
  args_json TEXT NOT NULL,             -- canonical JSON (sorted keys, no spaces), <= 64 KB
  args_hash TEXT NOT NULL,             -- sha256 hex of args_json
  category TEXT NOT NULL CHECK (category IN
    ('payment','message','public_post','delete','form_submit','upload','shell','memory','job','other')),
  summary TEXT NOT NULL,               -- generated by code, never by the model
  details TEXT NOT NULL,               -- JSON: structured facts shown in the card
  model_reason TEXT,                   -- the model's own "reason" arg, <= 300 chars, shown labelled
  tainted INTEGER NOT NULL,            -- run was tainted at request time
  needs_confirm INTEGER NOT NULL,      -- two-step confirm (payment, delete, public_post, message)
  screenshot_path TEXT,                -- workspace-relative, browser actions only
  status TEXT NOT NULL CHECK (status IN
    ('pending','approved','rejected','expired','cancelled','executed','failed')),
  created REAL NOT NULL,
  expires REAL NOT NULL,
  decided REAL,
  decision_note TEXT,                  -- Roland's optional note on reject (<= 500 chars)
  executed REAL,
  result_digest TEXT                   -- sha256 of tool result
);
CREATE INDEX approvals_status ON approvals(status, created);
CREATE INDEX approvals_chat ON approvals(chat_id, created);

CREATE TABLE audit_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts REAL NOT NULL,
  actor TEXT NOT NULL,                 -- 'agent' | 'roland' | 'system' | 'job:<id>'
  event TEXT NOT NULL,                 -- see 9.6
  run_id TEXT,
  chat_id INTEGER,
  tool TEXT,
  decision TEXT,                       -- 'safe' | 'gated' | 'forbidden' | 'approved' | 'rejected' | ...
  detail TEXT NOT NULL,                -- JSON, <= AUDIT_DETAIL_MAX_BYTES, secrets redacted
  prev_hash TEXT NOT NULL,
  hash TEXT NOT NULL                   -- sha256(prev_hash || canonical_json(row without hash))
);
CREATE INDEX audit_ts ON audit_log(ts);
CREATE INDEX audit_event ON audit_log(event, ts);
CREATE TRIGGER audit_no_update BEFORE UPDATE ON audit_log
  BEGIN SELECT RAISE(ABORT, 'audit_log is append-only'); END;
CREATE TRIGGER audit_no_delete BEFORE DELETE ON audit_log
  BEGIN SELECT RAISE(ABORT, 'audit_log is append-only'); END;

CREATE TABLE files (
  path TEXT PRIMARY KEY,               -- normalised workspace-relative path
  size INTEGER NOT NULL,
  sha256 TEXT,
  origin TEXT NOT NULL CHECK (origin IN ('upload','agent','sandbox','browser','unknown')),
  chat_id INTEGER,
  created REAL NOT NULL,
  updated REAL NOT NULL
);

CREATE TABLE trash (
  id TEXT PRIMARY KEY,
  original_path TEXT NOT NULL,
  trash_path TEXT NOT NULL,            -- under .trash/
  deleted_by TEXT NOT NULL,            -- 'roland' | 'agent'
  approval_id TEXT,
  size INTEGER NOT NULL,
  deleted REAL NOT NULL
);

CREATE TABLE signin_requests (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL,
  chat_id INTEGER,
  site TEXT NOT NULL,                  -- hostname, <= 253 chars
  url TEXT NOT NULL,                   -- http(s) only, <= 2048 chars
  reason TEXT,                         -- model's reason, <= 300 chars
  status TEXT NOT NULL CHECK (status IN ('pending','in_progress','done','cancelled','expired')),
  created REAL NOT NULL,
  expires REAL NOT NULL,
  finished REAL
);

CREATE TABLE screen_sessions (
  id TEXT PRIMARY KEY,
  session_hash TEXT NOT NULL,          -- sha256 of the login session token
  mode TEXT NOT NULL CHECK (mode IN ('watch','control')),
  signin_id TEXT,
  started REAL NOT NULL,
  last_seen REAL NOT NULL,
  ended REAL
);
"""


def apply(db: sqlite3.Connection) -> None:
    execute_script(db, SCHEMA)
